CREATE TABLE USERS(
   ID 		INTEGER PRIMARY KEY   AUTOINCREMENT,
   MAIL   	TEXT NOT NULL,
   PASSWORD TEXT NOT NULL,
   USERNAME TEXT NOT NULL,
   POINTS   INTEGER,
   SCHOOL	TEXT,
   CATEGORY	TEXT

);

CREATE TABLE NEWS(
   ID 			INTEGER PRIMARY KEY   AUTOINCREMENT,
   TITLE   		TEXT NOT NULL,
   CONTENT 		TEXT NOT NULL,
   LIKES		   INTEGER,
   POST_DATE  	TEXT,
   AUTHOR		INT

);

CREATE TABLE ADS(
   ID 			INTEGER PRIMARY KEY   AUTOINCREMENT,
   TITLE   		TEXT NOT NULL,
   CONTENT 		TEXT NOT NULL,
   AUTHOR 		INTEGER ,
   POST_DATE  	TEXT,
   RESOLVED		BOOLEAN

);

CREATE TABLE ANSWERS(
   ID 			INTEGER PRIMARY KEY   AUTOINCREMENT,
   CONTENT 		TEXT NOT NULL,
   AUTHOR 		INTEGER ,
   POST_DATE  	TEXT,
   PARENT		INTEGER
);

CREATE TABLE REQUESTS(
   ID       INTEGER PRIMARY KEY AUTOINCREMENT,
   MAIL     TEXT NOT NULL,
   PASSWORD TEXT NOT NULL,
   USERNAME TEXT NOT NULL,
   POINTS   INTEGER,
   SCHOOL   TEXT,
   CATEGORY TEXT

);

INSERT INTO USERS(MAIL,PASSWORD,USERNAME,POINTS,SCHOOL,CATEGORY)
VALUES('pierre@pierre.com','$2a$08$W.onbfN3MjJGuwnGj5ZA/usFVu7oM1ePE7nkDO6KAjpbdid8DBV2e','Pierre',0,'Mines','admin');

INSERT INTO REQUESTS(MAIL,PASSWORD,USERNAME,POINTS,SCHOOL,CATEGORY)
VALUES('pierre2@pierre.com','$2a$08$W.onbfN3MjJGuwnGj5ZA/usFVu7oM1ePE7nkDO6KAjpbdid8DBV2e','Pierre2',0,'Mines','admin');